CREATE TABLE IF NOT EXISTS counters (
  name TEXT PRIMARY KEY,
  value INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS country_visits (
  country_code TEXT PRIMARY KEY,
  visits INTEGER NOT NULL DEFAULT 0
);
